# For use with the Furey Lab CutNRun Snakemake pipeline 1.0.0

sampleInfo: "samplesheet.tsv"
#sampleInfoDelimiter: ","
#sampleName: ["sample"]


#Available Module Versions
module: 
	#wasp
	pythonVer: "python/3.9.6"
	#align
	bowtie2:
		bowtie2Ver: "bowtie2/2.4.5"
		bowtie2Index: "/proj/fureylab/genomes/human/refgenie/alias/hg38/bowtie2_index/default/hg38"
	#convertToBam, sortBam, nameSortBam 
	samtoolsVer: "samtools/1.21"
	#fastQC, fastQC after trim
	fastqcVer: "fastqc/0.12.1"  
	#fastqScreen
	fqscreen:
		fqscreenPath: "/proj/fureylab/bin/fastq_screen_0.14/fastq_screen"
		fqscreenConf: "/proj/fureylab/bin/fastq_screen_0.14/fastq_screen.conf"
	#trim_adapter
	cutadaptVer: "cutadapt/4.10"
	#markDups
	picard:
		picardVer: "picard/2.26.11"
	        picardPath: "/nas/longleaf/apps/picard/2.26.11/picard-2.26.11/picard.jar"
	#convertBamToBed, makeFragmentBedGraphs
	bedtoolsVer: "bedtools/2.30"
	#convertToBigWig
	ucscVer: "ucsctools/320"
	#callPeaks
	macsVer: "macs/2.2.9.1"
	seacrVer: 
	#qcReport
	multiqcVer: "multiqc/1.25.1"

#Target & Spike-in genome fasta Direct path
genome:
	human:
		fasta: ""
	e_coli:
		fasta: ""
	spikein:
		fasta: ""

#Direct path to genotype directory
genotype_dir: "/proj/fureylab/data/Genotypes/human/imputed_vcfs_hg38"

#Moves final results files for locally run samples to permenant space.
#NOTE: set to TRUE after running the pipeline, checking that everything had run correctly,
#      and the rerun the pipeline using the same submission statement.
moveOutFiles: FALSE


#Direct path to permenant space for moving out final files.
projectDir: ""
